### ISSUE TITLE
Is any existing example for CompositeBuilder

### ISSUE THREAD

**Issue by dotnfc** [STMicroelectronics/stm32_mw_usb_device#10]
i found the new class/CompositeBuilder, any example to show how to use it?

**Comment by ALABSTM** [comment]
Hi @dotnfc,

Please have a look at [this](https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/discussions/18) post. USB Device **Composite Class** applications running on `STM32H743I-EVAL` boards have been released since a while. I hope you find what you are looking for. Let me know otherwise.

With regards,
